FROM alpine:latest

RUN mkdir /dockerfiles

WORKDIR /app

COPY . /dockerfiles

ENV EULA=false \
    SEED=-7649949940957896961 \
    RCONPASS=mypass

RUN     apk update && \
        apk add libudev-zero && \
        apk add openjdk21-jre-headless && \
        rm -rf /var/cache/apk/* && \
        chmod +x /dockerfiles/docker-entrypoint.sh && \
        wget -O /bin/rcon-cli https://github.com/itzg/rcon-cli/releases/download/1.7.0/rcon-cli_1.7.0_linux_amd64.tar.gz && \
        tar -xzf /bin/rcon-cli -C /bin rcon-cli

EXPOSE 25565 25575

VOLUME /app

ENTRYPOINT ["sh" , "/dockerfiles/docker-entrypoint.sh"]

CMD [""]
